### ISSUE TITLE
Scrolling to the bottom

### ISSUE THREAD

**Issue by AbdelilahLbardi** [buzinas/simple-scrollbar#12]
Hello,

I have a DIV that load messages by default from the database. I want to know how can i make the scroll bar by default in the bottom and also scroll to the bottom for after each append to my specific DIV.

Regards,

**Comment by buzinas** [comment]
Supposing your div is something like:
```html
<div id="dataFromDB" ss-container></div>
```
You'll have to do:
```javascript
var scrollContainer = document.getElementById('dataFromDB').querySelector('.ss-content');
scrollContainer.scrollTop = scrollContainer.scrollHeight;
```

And everytime you append a child you can call that too. If you don't want to append it manually, you would have to use [Mutation observers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) or something like that.

By the way, the children that you want to append to your div, should be added to this `.ss-content` div as well - not sure if you're doing that.

**Comment by AbdelilahLbardi** [comment]
Thank you @buzinas
