### ISSUE TITLE
Not work with height in %

### ISSUE THREAD

**Issue by bluegaurav** [buzinas/simple-scrollbar#27]
`<div style="height: 20%; width: 200px; display: inline-block;" ss-container>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>`

If i change height attribute value from 300 px to 20% it stop working  :cry:

**Comment by buzinas** [comment]
Yes, that's true. I'm glad to accept a PR for this, but I won't touch it for now.
