### ISSUE TITLE
original scroll is not hidden

### ISSUE THREAD

**Issue by yalwayzm33** [buzinas/simple-scrollbar#28]
original scroll is also shown with simple-scroll bar how to remove it

**Comment by Mikecoon** [comment]
This piece of junk just doens't work at all.
All thing it do is adds extra padding to ss-container and that's all.

**Comment by Mikecoon** [comment]
Finally, I fixed it. So if you're a such a good boy and use this "simple" scroll to your body element, the prefer way to make it work is to change css:

```
height: 100%;
    width: calc(100% + 18px);
    position: relative;
    right: 0;
    overflow: auto;
    box-sizing: border-box;
```

Also, you have to make your body is `height: 100vh;`

**Comment by moonlight-team** [comment]
Be mindful of your language toward the creator, and use constructive criticism. If you don't like it so much please use something else. :)

**Comment by Mikecoon** [comment]
So in own your world, providing fix isn't constructive enough?
