### ISSUE TITLE
Bar should not disappear when dragging and moving mouse out of parent component

### ISSUE THREAD

**Issue by mikerockett** [buzinas/simple-scrollbar#34]
![simple-scrollbar](https://user-images.githubusercontent.com/4586280/32838445-987be156-ca19-11e7-8b39-27ceba1eda99.gif)

**Comment by buzinas** [comment]
Thanks for reporting. I won't fix it, but would be glad to accept a PR for this.

**Comment by jlmakes** [comment]
#32
