### ISSUE TITLE
Scrollbar should stay visible while dragging

### ISSUE THREAD

**Issue by 1j01** [buzinas/simple-scrollbar#39]
In the demo it disappears when you leave the container, but it should stay if you're dragging the scrollbar.

![quantum scrollbar](https://user-images.githubusercontent.com/3630663/36862095-dc7634e6-1d53-11e8-8b6e-92727a0313bb.gif)

**Comment by buzinas** [comment]
Hey, thanks for reporting this! Do you wanna go ahead and create a PR fixing it?

**Comment by 1j01** [comment]
No

**Comment by buzinas** [comment]
Np, then! Have a good one :)
