### ISSUE TITLE
Not working with max-height

### ISSUE THREAD

**Issue by ismailfarooq** [buzinas/simple-scrollbar#4]

**Comment by buzinas** [comment]
Could you throw a jsfiddle, so I can take a look?

**Comment by ismailfarooq** [comment]
http://jsbin.com/woweyurihi/edit?html,css,js,output

if you replace max-height with height the plugin will work

**Comment by buzinas** [comment]
OK, now it should work as expected! :)

**Comment by ismailfarooq** [comment]
Thanks its working now :)
