### ISSUE TITLE
Make HTML5 compliant

### ISSUE THREAD

**Issue by d2a-raudenaerde** [buzinas/simple-scrollbar#54]
When validating your library for HTML5 compliancy, there are errors:

> Error: Attribute ss-container not allowed on element div at this point.
> 
> From line 14, column 5; to line 14, column 82
> 
> ></a>↩    <div style="height: 300px; width: 200px; display: inline-block;" ss-container>↩     
> 
> Attributes for element div:

I think the 'ss-container' should be replaced by, for example, 'data-ss-container' 

See here: https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute

**Comment by buzinas** [comment]
The only custom attribute we add is `data-simple-scrollbar`, `ss-container` is just a class name.
