### ISSUE TITLE
So is this thing mobile friendly?

### ISSUE THREAD

**Issue by Puddingboy** [buzinas/simple-scrollbar#6]
Will touch gestures make the scrollbar move or will it ignore touch untill I use hammer or some other library? I am not sure if we understand the same thing with the word native.

*edit: Your use of mousedown, mouseup and mousemove would suggest it is. I just don't want this to be too good to be true

**Comment by buzinas** [comment]
It works with mobile touches exactly the same way as native scrollbars do.
Em 05/06/2016 13:30, "Puddingboy" <notifications@github.com> escreveu:

**Comment by Puddingboy** [comment]
Roger that. I did test it with my phone on your demo, but I did notice that the body background scrolled aswell. I suppose I would have to block background scrolling somehow. Do you have any ideas to make this work? So while simple-scrollbar is scrolling other content is blocked from scrolling?

**Comment by buzinas** [comment]
If you want that behavior, you can put the following css rule there:
```css
body {
  overflow: hidden;
}
```
Em 05/06/2016 15:40, "Puddingboy" <notifications@github.com> escreveu:

**Comment by Puddingboy** [comment]
I think I like that approach. I found a different suggestion that blocks the event using javascript, but I think using js to change the overflow property temporary may be a an even better idea.

**Comment by Puddingboy** [comment]
Oh I'm not sure if it was clear from my last comment but what I meant was that if you have a page with a regular scrollbar and you put the overflow on hidden, the scrollbar disappears and the x offset of the page may jump a little.
