### ISSUE TITLE
Position of scrollbar

### ISSUE THREAD

**Issue by VitaliyR** [buzinas/simple-scrollbar#9]
Hi there!

I'm wondering why do you use `position: relative` and `style: right: -Npx` for `.ss-scroll`? 

Why not usual relative/absolute? 

I tried to use it, and out of the box the scrollbar was sticked to top.

**Comment by VitaliyR** [comment]
W/o explanation? Thanks.

**Comment by buzinas** [comment]
@VitaliyR Sorry, I thought I answered.

There is no particular reason for using negative right, and I don't understand why you think it's not usual (at least, for me, it's something I've used many times.

I don't understand your problem, also. Do you have a jsFiddle or something like that to show me what's the problem? It would be nice to tell me what is the OS and browser either.

**Comment by VitaliyR** [comment]
I see.

I think the problem is caused by flex container. I tried to init the plugin on it.

**Comment by buzinas** [comment]
Any news?

**Comment by VitaliyR** [comment]
@buzinas I can't reproduce and while trying to do so I'm reaching new bugs - somewhy `ss-hidden` class is added to scrollbar. Plugin decides that scroll doesn't needed there. 

Anyway, I have a structure:
2 column flex
1
2 - 2 row flex
      1 
      2 - flex .... flex ... container with scroll. And here content scrolls fine, but the scrollbar div `ss-scrollbar` is staying at the top of container, but it's style attributes are changing (top in % etc).

**Comment by buzinas** [comment]
Can I close this?

**Comment by VitaliyR** [comment]
@buzinas I think yes. But, anyway, there are very strange behaviors under latest Chrome (53.0.2785.143 (64-bit)) using complex flexbox layouts.
